import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Background from '../components/background'

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Kenton Web Agency</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Background />
		</div>
	)
}

export default Home
