import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Background from '../components/background'
import AboutUs from '../components/about-us'

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Kenton Web Agency</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Background />

			<AboutUs />
		</div>
	)
}

export default Home
